language: groovy
jdk:
 - oraclejdk7

before_script:
 - chmod +x grailsw

script: ./grailsw refresh-dependencies
 && ./grailsw test-app


notifications:
  email:
    - couturier.jeremie@hotmail.fr
    - gautier.pelloux@gmail.com
    - jeremi.jutand@hotmail.fr
    - fourel.david118@gmail.com

deploy:
  provider: heroku
  api_key: 12c43751-47de-4f30-bdc7-8f95e3e221b2
  app: outofbounds

   
