language: groovy
jdk:
 - oraclejdk7

 notifications:
  email:
    - couturier.jeremie@hotmail.fr

before_script:
 - chmod +x grailsw

script: ./grailsw refresh-dependencies
 && ./grailsw "test-app -integration"
