language: groovy
jdk:
 - oraclejdk7

before_script:
 - chmod +x grailsw

script: ./grailsw refresh-dependencies
 && ./grailsw "test-app -integration"


notifications:
  email:
    - couturier.jeremie@hotmail.fr
    - gauthier.pelloux@gmail.com
    - jeremi.jutand@hotmail.fr
    - fourel.david118@gmail.com